---
repos:
  - repo: local
    hooks:
      - id: super-linter
        name: super-linter
        language: system
        entry: make super-linter-fix
        pass_filenames: false
      - id: make-test
        name: make test
        language: system
        entry: make test
        pass_filenames: false
