# zizmor configuration file for Super-Linter
# See https://docs.zizmor.sh/configuration/ for options

rules:
  dangerous-triggers:
    ignore:
      - ".github/workflows/pr-title-check.yaml"
  secrets-outside-env:
    ignore:
      - ".github/workflows/tag.yaml"
      - ".github/workflows/tests.yaml"
  artipacked:
    ignore:
      - ".github/workflows/tag.yaml"
