---
name: Lint Code Base

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Run Super-Linter
    permissions:
      contents: write
      issues: write
      statuses: write
      pull-requests: write
      packages: read
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout The Source Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Load Super-Linter Environment
        run: |
          grep -v '^#' .github/super-linter.env >> "$GITHUB_ENV"

      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pre-commit:
    name: Run Pre-commit Hooks
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Checkout The Source Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: 'pyproject.toml'

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Prepare environment
        run: |
          make dev
          make setup-precommit

      - name: Run Pre-commit Hooks
        run: |
          export SKIP="textlint,super-linter"
          make precommit
