---
name: Run Tests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".coveragerc"
      - ".github/workflows/tests.yaml"
      - "Makefile"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".coveragerc"
      - ".github/workflows/tests.yaml"
      - "Makefile"
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: Tests
    runs-on: ubuntu-slim
    timeout-minutes: 10
    env:
      PYTHON_COVERAGE_LIMIT: 90
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout The Source Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Run tests
        run: make test 2>&1 | tee pytest-coverage.txt
        env:
          PYTEST_ADDOPTS: "--cov-report=xml --junitxml=junit.xml -o junit_family=legacy"

      - name: Read coverage
        id: coverage
        run: |
          COVERAGE=$(awk '/^TOTAL/ {print $(NF)}' pytest-coverage.txt | tr -d '%')
          echo "value=$COVERAGE" >> "$GITHUB_OUTPUT"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # zizmor: ignore[secrets-outside-env]

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # zizmor: ignore[secrets-outside-env]
          files: ./junit.xml
          report_type: test_results

      - name: Fail if coverage too low
        if: ${{ fromJSON(steps.coverage.outputs.value) < fromJSON(env.PYTHON_COVERAGE_LIMIT) }}
        run: |
          echo "Coverage is below ${{ env.PYTHON_COVERAGE_LIMIT }}%!"
          exit 1
